"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."

"preserve_hierarchy": true

"files": [
  {
    "source": "README.md",
    "translation": "readme/README-%two_letters_code%.md",
      "languages_mapping": {
        "two_letters_code": {
          "zh-CN": "cn",
          "nl": "nl",
          "fr": "fr",
          "ja": "ja",
          "ko": "ko",
          "es": "es",
          "ar": "ar",
          "pt": "pt",
          "ru": "ru",
          "sv": "sv",
          "de": "de",
          "es-ES": "es"
        }
      }
  }
]