name: Translate README

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'
  workflow_dispatch:

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Translate README.md to Spanish
      run: |
        TEXT=$(cat README.md)
        RESPONSE=$(curl -X POST "https://libretranslate.com/translate" \
                      -F "q=$TEXT" \
                      -F "source=en" \
                      -F "target=es" \
                      -F "format=text")
        echo "Server Response: $RESPONSE"  # This will print the server response for debugging
        TRANSLATED_TEXT=$(echo "$RESPONSE" | jq -r .translatedText)
        echo "$TRANSLATED_TEXT" > README.es.md


    - name: Commit and push translated README
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.es.md
        git commit -m "Add translated README.es.md"
        git push
